[accessibility]
ui_scale = 1.0500000081956387

[audio]
enable_sounds = true

[bar.default]
background_opacity = 0.4999999888241291
center = []
end = [
    "media",
    "status",
    "tray",
    "clipboard",
    "notifications",
    "network",
    "bluetooth",
    "volume",
    "battery",
    "control-center",
    "clock",
    "session"
]
margin_ends = 0
start = [ "launcher", "workspaces", "todo", "widget" ]
thickness = 25
widget_spacing = 10

[desktop_widgets]
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001", "desktop-widget-0000000000000002" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 195.0
    cy = 962.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "media_player"

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 96.0
    box_width = 208.0
    cx = 130.5
    cy = 828.79998779296875
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "weather"

[dock]
background_opacity = 0.94999999999999996

[location]
auto_locate = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003",
    "lockscreen-widget-0000000000000004"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 128.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = false
        show_login_button = false
        show_media = false
        show_session_buttons = true
        show_unlock_hint = false
        show_weather = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 96.0
    box_width = 176.0
    cx = 104.0
    cy = 828.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "weather"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 0.0
    box_width = 0.0
    cx = 192.0
    cy = 962.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "media_player"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
    box_height = 96.0
    box_width = 160.0
    cx = 285.0
    cy = 828.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000004.settings]
        clock_style = "digital"
        timezone = ""

[nightlight]
enabled = true

[notification]
background_opacity = 0.94999999999999996
layer = "overlay"

[osd]
background_opacity = 0.94999999999999996

[plugin_settings."noctalia/notes"]
notes_dir = "~/Documents"

[plugin_settings."noctalia/translator"]
target_lang = "ru"

[plugin_settings."noctalia/wallhaven"]

[plugins]
enabled = [
    "noctalia/kaomoji",
    "noctalia/translator",
    "noctalia/wallhaven",
    "reaperhound/ambient-sounds",
    "aristides/udiskie",
    "yocraft/web-launcher"
]

[shell]
avatar_path = "/home/jim/Projects/nix/wallpapers/avatar/f1127010328.png"
corner_radius_scale = 1.8000000268220901
font_family = "JetBrains Mono"
password_style = "random"
polkit_agent = true
screen_time_enabled = true

    [shell.animation]
    speed = 1.1500000171363354

    [shell.launcher]
    categories = false
    compact = true

    [shell.mpris]
    blacklist = [ "Mozilla librewolf" ]

    [shell.panel]
    transparency_mode = "solid"

    [shell.screen_corners]
    enabled = true

[theme]
builtin = "Tokyo-Night"
community_palette = "ADW"
custom_palette = "stylix"
mode = "dark"
shell_mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

    [theme.templates]
    enable_builtin_templates = false
    enable_community_templates = false

[wallpaper]
directory = "/home/jim/Projects/nix/wallpapers"
transition_on_startup = true

    [wallpaper.automation]
    enabled = true
    recursive = false

    [wallpaper.default]
    path = "/home/jim/Projects/nix/wallpapers/wallhaven-w5d7oq.jpg"

    [wallpaper.last]
    path = "/home/jim/Projects/nix/wallpapers/wallhaven-w5d7oq.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/jim/Projects/nix/wallpapers/wallhaven-w5d7oq.jpg"

    [[wallpaper.favorite]]
    builtin_palette = "Tokyo-Night"
    palette_source = "builtin"
    path = "/home/jim/Projects/nix/wallpapers/wallhaven-eolk1l.jpg"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    builtin_palette = "Tokyo-Night"
    palette_source = "builtin"
    path = "/home/jim/Projects/nix/wallpapers/wallhaven-dg82zl.jpg"
    theme_mode = "dark"

[widget.battery]
hide_when_full = true
hide_when_plugged = true

[widget.clipboard]
enabled = false

[widget.control-center]
enabled = false

[widget.launcher]
glyph = "rocket"

[widget.network]
show_label = false

[widget.status]
type = "aristides/udiskie:status"

[widget.todo]
type = "nightwatch75/todo:todo"

[widget.widget]
type = "aabidk20/yt-music:widget"

[widget.workspaces]
scale = 1.1000000000000001
show_labels = true
